import XCTest
@testable import XCLocSmithKit

/// The parser and writer are the only things standing between this tool and
/// someone's irreplaceable translation file, so they are pinned hard.
final class JSONTests: XCTestCase {

    // MARK: - Round-trip fidelity

    /// Written in Xcode's exact style: two-space indent, `"key" : value`,
    /// escaped forward slashes, expanded empty objects, keys in Unicode order.
    private let xcodeFormatted = """
        {
          "sourceLanguage" : "en",
          "strings" : {
            "" : {

            },
            "\\"quoted\\"" : {
              "extractionState" : "stale"
            },
            "%lld items" : {
              "localizations" : {
                "ru" : {
                  "substitutions" : {
                    "count" : {
                      "argNum" : 1,
                      "formatSpecifier" : "lld",
                      "variations" : {
                        "plural" : {
                          "one" : {
                            "stringUnit" : {
                              "state" : "translated",
                              "value" : "%lld \u{448}\u{442}\u{443}\u{43A}\u{430}"
                            }
                          },
                          "other" : {
                            "stringUnit" : {
                              "state" : "translated",
                              "value" : "%lld \u{448}\u{442}\u{443}\u{43A}"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "Plain" : {
              "comment" : "A comment",
              "isCommentAutoGenerated" : true,
              "localizations" : {
                "ja" : {
                  "stringUnit" : {
                    "state" : "translated",
                    "value" : "\u{65E5}\u{672C}\u{8A9E}"
                  }
                }
              }
            },
            "See https:\\/\\/example.com\\/docs" : {
              "shouldTranslate" : false
            }
          },
          "version" : "1.0"
        }

        """

    func testRoundTripIsByteIdentical() throws {
        let parsed = try JSONParser.parse(xcodeFormatted)
        XCTAssertEqual(JSONWriter.text(parsed, style: .xcode), xcodeFormatted)
    }

    func testUnknownFieldsSurvive() throws {
        let source = """
            {"strings":{"K":{"futureField":{"nested":[1,true,null]}}},"sourceLanguage":"en"}
            """
        let catalog = try Catalog(path: try write(source, named: "Localizable.xcstrings"))
        let reparsed = try JSONParser.parse(catalog.serialized())
        let future = reparsed["strings"]?["K"]?["futureField"]?["nested"]?.arrayValue
        XCTAssertEqual(future, [.number("1"), .bool(true), .null])
    }

    func testNumbersKeepTheirSpelling() throws {
        let parsed = try JSONParser.parse(#"{"a":1.0,"b":1e3,"c":-0.5}"#)
        XCTAssertEqual(parsed["a"], .number("1.0"))
        XCTAssertEqual(parsed["b"], .number("1e3"))
        XCTAssertEqual(parsed["c"], .number("-0.5"))
    }

    // MARK: - Strictness

    /// A merge conflict resolved badly leaves two entries for one key. Last-wins
    /// would silently drop a translation, so this is an error.
    func testDuplicateKeysAreRejected() {
        XCTAssertThrowsError(try JSONParser.parse(#"{"Save":{"a":1},"Save":{"b":2}}"#)) { error in
            XCTAssertTrue("\(error)".contains("duplicate key"), "\(error)")
        }
    }

    /// NFC and NFD spellings are distinct JSON keys but equal Swift strings;
    /// silently collapsing them deletes one translation.
    func testCanonicallyEquivalentKeysAreRejected() {
        let nfc = "Caf\u{00E9}"
        let nfd = "Cafe\u{0301}"
        XCTAssertThrowsError(try JSONParser.parse(#"{"\#(nfc)":{},"\#(nfd)":{}}"#)) { error in
            XCTAssertTrue("\(error)".contains("duplicate key"), "\(error)")
        }
    }

    func testMalformedNumbersAreRejected() {
        for malformed in ["{\"a\":1e+}", "{\"a\":-}", "{\"a\":+5}", "{\"a\":1.2.3}", "{\"a\":01}"] {
            XCTAssertThrowsError(try JSONParser.parse(malformed), "accepted \(malformed)")
        }
    }

    func testLoneSurrogateIsRejected() {
        XCTAssertThrowsError(try JSONParser.parse(#"{"a":"\ud800"}"#))
    }

    func testSurrogatePairDecodes() throws {
        let parsed = try JSONParser.parse(#"{"a":"🧖"}"#)
        XCTAssertEqual(parsed["a"]?.stringValue, "🧖")
    }

    func testDeepNestingIsRejectedRatherThanCrashing() {
        let depth = JSONParser.maximumDepth + 10
        let payload = String(repeating: "[", count: depth) + String(repeating: "]", count: depth)
        XCTAssertThrowsError(try JSONParser.parse(payload)) { error in
            XCTAssertTrue("\(error)".contains("nesting"), "\(error)")
        }
    }

    func testErrorsReportLineAndColumn() {
        XCTAssertThrowsError(try JSONParser.parse("{\n  \"a\" : ,\n}")) { error in
            guard let parseError = error as? JSONParseError else { return XCTFail("wrong error") }
            XCTAssertEqual(parseError.line, 2)
        }
    }

    func testControlCharactersAreEscapedOnWrite() {
        let value = JSONValue.object(["a": .string("tab\tbell\u{07}")])
        let rendered = JSONWriter.text(value)
        // No raw control character survives into the file.
        XCTAssertFalse(rendered.unicodeScalars.contains { $0.value < 0x20 && $0 != "\n" })
        // The bell becomes a \u escape.
        XCTAssertTrue(rendered.contains("u0007"))
        XCTAssertTrue(rendered.contains("tab") && rendered.contains("bell"))
    }

    // MARK: - Helpers

    private func write(_ contents: String, named name: String) throws -> String {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let path = directory.appendingPathComponent(name).path
        try contents.write(toFile: path, atomically: true, encoding: .utf8)
        return path
    }
}
